{
 "title": "Vue générale de la météo actuelle",
 "time": { "from": "2024-10-14T00:00:00.000Z", "to": "2024-10-15T00:00:00.000Z" },
 "panels": [
  {
   "title": "Vitesse du vent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wind_speed \nFROM weather \nWHERE city = 'Paris' \nORDER BY date DESC \nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT humidity \nFROM weather \nWHERE city = 'Paris' \nORDER BY date DESC \nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Température actuelle",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date, temperature_max \nFROM weather \nWHERE city = 'Paris' \nORDER BY date DESC \nLIMIT 30;\n"
    }
   ]
  }
 ]
}